# Generated by Django 4.2.8 on 2023-12-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='uuid',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=123454378654, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
