# Generated by Django 4.2.8 on 2024-01-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
