# Generated by Django 4.2.8 on 2024-01-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_delete_variationmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='carts.variation'),
        ),
    ]
