# Generated by Django 4.2.8 on 2023-12-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_numbre',
            field=models.CharField(max_length=120),
        ),
    ]
