# Generated by Django 4.2.8 on 2023-12-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_phone_numbre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_actif',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
    ]
